import { motion } from "framer-motion";
import { ArrowRight, Check, Github, Layers3, ShieldCheck, Sparkles, Terminal, Workflow, Zap } from "lucide-react";
import { Link } from "react-router";
import { useAuth } from "@/hooks/use-auth";

const capabilities = [
  { icon: Terminal, title: "Start coding work", text: "Turn a plain-English prompt into a Jules session against any connected repository." },
  { icon: Workflow, title: "Stay in the loop", text: "Watch plans, progress updates, messages, and artifacts arrive in one focused timeline." },
  { icon: Github, title: "Ship with context", text: "Choose a branch, approve plans, guide Jules, and open the resulting pull request." },
];

export default function Landing() {
  const { isAuthenticated } = useAuth();
  return <div className="min-h-screen overflow-hidden bg-[#f7f8fa] text-slate-950">
    <div className="pointer-events-none absolute inset-x-0 top-0 h-[620px] bg-[radial-gradient(circle_at_50%_-10%,rgba(37,99,235,0.12),transparent_56%)]" />
    <header className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8 lg:px-10"><Link to="/" className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-slate-950 text-white"><Sparkles className="size-4" /></div><div><div className="text-sm font-semibold tracking-tight">Julespace</div><div className="text-[9px] font-medium uppercase tracking-[0.18em] text-slate-400">Personal console</div></div></Link><nav className="hidden items-center gap-8 text-xs font-medium text-slate-500 sm:flex"><a href="#how-it-works" className="hover:text-slate-950">How it works</a><a href="https://jules.google/docs/api/reference/" target="_blank" rel="noreferrer" className="hover:text-slate-950">API reference</a></nav><Link to={isAuthenticated ? "/dashboard" : "/auth"} className="flex items-center gap-2 rounded-lg bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white transition-colors hover:bg-slate-800">{isAuthenticated ? "Open console" : "Get started"}<ArrowRight className="size-3.5" /></Link></header>
    <main className="relative"><section className="mx-auto max-w-5xl px-5 pb-24 pt-20 text-center sm:px-8 sm:pt-28"><div className="mx-auto mb-6 flex w-fit items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-blue-700"><span className="size-1.5 rounded-full bg-blue-500" />A better way to work with Jules</div><h1 className="mx-auto max-w-4xl text-5xl font-semibold leading-[0.98] tracking-[-0.07em] text-slate-950 sm:text-7xl">Your command center<br /><span className="text-blue-600">for coding with Jules.</span></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-slate-500 sm:text-lg">A polished personal workspace for starting sessions, watching progress, guiding the agent, and getting your changes ready to ship.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to={isAuthenticated ? "/dashboard" : "/auth"} className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-slate-950 px-6 text-sm font-semibold text-white hover:bg-slate-800">{isAuthenticated ? "Open your workspace" : "Launch Julespace"}<ArrowRight className="size-4" /></Link><a href="https://jules.google/docs/api/reference/" target="_blank" rel="noreferrer" className="inline-flex h-11 items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-6 text-sm font-semibold text-slate-700 hover:bg-slate-50">Read the API reference</a></div></section>
      <section className="mx-auto max-w-6xl px-5 pb-24 sm:px-8"><div className="relative overflow-hidden rounded-3xl border border-slate-200 bg-slate-950 p-3 sm:p-5"><div className="absolute -right-20 -top-20 size-72 rounded-full bg-blue-500/20 blur-3xl" /><div className="relative rounded-2xl border border-white/10 bg-[#101722] p-5 sm:p-8"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-lg bg-white/10 text-white"><Sparkles className="size-4" /></div><div><div className="text-xs font-semibold text-white">Julespace</div><div className="text-[9px] uppercase tracking-[0.16em] text-slate-500">Personal console</div></div></div><div className="flex gap-1.5"><span className="size-2 rounded-full bg-white/20" /><span className="size-2 rounded-full bg-white/20" /><span className="size-2 rounded-full bg-white/20" /></div></div><div className="grid gap-4 pt-6 sm:grid-cols-[.8fr_1.2fr]"><div className="rounded-xl border border-white/10 bg-white/[0.04] p-5 text-left"><div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-blue-300">Active session</div><div className="mt-4 text-lg font-semibold text-white">Add auth tests</div><div className="mt-2 text-xs leading-5 text-slate-400">Jules is writing comprehensive tests for the authentication module.</div><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-2/3 rounded-full bg-blue-500" /></div><div className="mt-2 flex justify-between text-[10px] text-slate-500"><span>Writing tests</span><span>66%</span></div></div><div className="rounded-xl border border-white/10 bg-white/[0.04] p-5 text-left"><div className="flex items-center justify-between"><div className="text-xs font-semibold text-white">Activity timeline</div><span className="flex items-center gap-1.5 text-[10px] text-emerald-300"><span className="size-1.5 rounded-full bg-emerald-400" />Live</span></div><div className="mt-5 space-y-5">{[["Plan generated", "Review existing auth module", "10:31"], ["Jules", "Creating test cases for login", "10:42"], ["You", "Also cover the magic link flow", "10:45"]].map(([label, text, time], index) => <div className="flex gap-3" key={label}><div className={`mt-1 size-2 shrink-0 rounded-full ${index === 1 ? "bg-blue-400" : "bg-white/30"}`} /><div className="flex-1"><div className="flex justify-between gap-3 text-[11px] font-medium text-slate-300"><span>{label}</span><span className="text-slate-600">{time}</span></div><div className="mt-1 text-[11px] text-slate-500">{text}</div></div></div>)}</div></div></div></div></div></section>
      <section id="how-it-works" className="mx-auto max-w-6xl px-5 pb-28 sm:px-8"><div className="mb-10 max-w-lg"><div className="mb-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-blue-600">Everything Jules offers</div><h2 className="text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">Less context switching.<br />More work shipped.</h2><p className="mt-4 text-sm leading-6 text-slate-500">Version one stays intentionally focused: a beautiful interface over the complete Jules API, built for one person and their code.</p></div><div className="grid gap-4 md:grid-cols-3">{capabilities.map(({ icon: Icon, title, text }, index) => <motion.div initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex size-10 items-center justify-center rounded-xl bg-slate-100 text-slate-700"><Icon className="size-5" /></div><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></motion.div>)}</div></section>
      <section className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-8 px-5 py-16 sm:flex-row sm:items-center sm:px-8"><div><div className="flex items-center gap-2 text-xs font-semibold text-slate-700"><ShieldCheck className="size-4 text-emerald-600" />Your API key stays server-side</div><p className="mt-2 max-w-md text-xs leading-5 text-slate-400">Connect with your Jules API key through the project Keys/API keys tab. Julespace never exposes it in the browser.</p></div><Link to={isAuthenticated ? "/dashboard" : "/auth"} className="inline-flex w-fit items-center gap-2 rounded-lg bg-blue-600 px-5 py-3 text-xs font-semibold text-white hover:bg-blue-700">{isAuthenticated ? "Go to dashboard" : "Create your workspace"}<ArrowRight className="size-3.5" /></Link></div></section>
    </main><footer className="mx-auto flex max-w-7xl items-center justify-between px-5 py-7 text-[11px] text-slate-400 sm:px-8"><span>Julespace · A personal Jules console</span><span className="flex items-center gap-1.5"><Zap className="size-3 text-blue-500" />Built for focused work</span></footer>
  </div>;
}
